# Auto-generated county mappings from state cleaners
COMPREHENSIVE_COUNTY_MAPPINGS = {
    'Ak': 'Alaska',
    'Wv': 'West Virginia',
    'Ca': 'California',
    'De': 'Delaware',
    'In': 'Indiana',
    'Dc': 'District of Columbia',
    'Sd': 'South Dakota',
    'Bldg. A Homer': 'Homer',
    'N': 'New Castle',
    'S': 'Sussex',
    'K': 'Kent',
    'NK': 'New Castle/Kent',
    'KS': 'Kent/Sussex',
    'N,K': 'New Castle/Kent',
    'K, S': 'Kent/Sussex',
    'N, K': 'New Castle/Kent',
    'N/K': 'New Castle/Kent',
    'Nk': 'New Castle County',
    'Ks': 'Kent County',
    'N,k': 'New Castle County',
    'N/k': 'New Castle County',
}
