# Auto-generated office mappings from state cleaners
COMPREHENSIVE_OFFICE_MAPPINGS = {
    'PRESIDENT': 'US President',
    'US PRESIDENT': 'US President',
    'U.S. REPRESENTATIVE': 'US Representative',
    'US REPRESENTATIVE': 'US Representative',
    'U.S. SENATOR': 'US Senator',
    'US SENATOR': 'US Senator',
    'GOVERNOR': 'Governor',
    'SHERIFF': 'Sheriff',
    'WILMINGTON CITY COUNCIL AT LARGE': 'City Council Member At-Large',
    'WILMINGTON CITY COUNCIL': 'City Council Member',
    'COUNTY COUNCIL MEMBER': 'County Council Member',
    'COUNTY LEVY COURT MEMBER': 'County Levy Court Member',
    'COUNTY CLERK OF THE PEACE': 'County Clerk of the Peace',
    'COUNTY REGISTER OF WILLS': 'County Register of Wills',
    'STATE REPRESENTATIVE': 'State Representative',
    'STATE SENATOR': 'State Senator',
    'STATE REP': 'State Representative',
    'STATE SEN': 'State Senator',
    'attorney general': 'State Attorney General',
    'governor': 'State Governor',
    'lieutenant governor': 'State Lieutenant Governor',
    'secretary of state': 'State Secretary of State',
    'state auditor': 'State Auditor',
    'state treasurer': 'State Treasurer',
    'us representative': 'US Representative',
    'us senator': 'US Senator',
    'state senator': 'State Senate',
    'state representative': 'State House',
    'state house': 'State House',
    'state senate': 'State Senate',
}
