# Auto-generated party mappings from state cleaners
COMPREHENSIVE_PARTY_MAPPINGS = {
    'democrat': 'Democratic',
    'republican': 'Republican',
    'independent': 'Independent',
    'libertarian': 'Libertarian',
    'green': 'Green',
    'constitution': 'Constitution',
    'reform': 'Reform',
    'natural law': 'Natural Law',
    'socialist': 'Socialist',
    'communist': 'Communist',
    'american independent': 'American Independent',
    'peace and freedom': 'Peace and Freedom',
    'working families': 'Working Families',
    'women\'s equality': 'Women\'s Equality',
    'independence': 'Independence',
    'conservative': 'Conservative',
    'liberal': 'Liberal',
    'moderate': 'Moderate',
    'progressive': 'Progressive',
    'tea party': 'Tea Party',
    'no party preference': 'No Party Preference',
    'nonpartisan': 'Nonpartisan',
    'unaffiliated': 'Unaffiliated',
    'decline to state': 'Decline to State',
    'write-in': 'Write-in',
    'other': 'Other',
    'dem': 'Democratic',
    'rep': 'Republican',
    'ind': 'Independent',
    'lib': 'Libertarian',
    'grn': 'Green',
    'con': 'Constitution',
    'ref': 'Reform',
    'nat': 'Natural Law',
    'soc': 'Socialist',
    'com': 'Communist',
    'aip': 'American Independent',
    'paf': 'Peace and Freedom',
    'wfp': 'Working Families',
    'we': 'Women\',
    'mod': 'Moderate',
    'prog': 'Progressive',
    'tp': 'Tea Party',
    'npp': 'No Party Preference',
    'non': 'Nonpartisan',
    'una': 'Unaffiliated',
    'dts': 'Decline to State',
    'DEMOCRATIC': 'Democratic',
    'CONSTITUTION PARTY OF ILLINOIS': 'Constitution',
    'SOCIALIST PARTY USA': 'Socialist',
    'INDEPENDENT CONSERVATIVE': 'Independent',
    'SOCIALIST EQUALITY': 'Socialist',
    'TOGETHER ENHANCING AMERICA': 'Other',
    'TEA': 'Tea Party',
    'ILLINOIS GREEN': 'Green',
    'AMERICAN SOLIDARITY PARTY': 'Other',
    'PARTY FOR SOCIALISM AND LIBERATION': 'Socialist',
    'WORKING CLASS PARTY': 'Socialist',
    'GREENER PEACE UNITED': 'Green',
    'JOBS': 'Other',
    'REFORM PARTY OF ILLINOIS': 'Reform',
    'HIRAM CRAWFORD POLITICAL': 'Other',
    'DEATH TO CONGRESS': 'Other',
    'HONESTY & INTEGRITY': 'Other',
    'RPIL': 'Other',
    'WORKING TAXPAYERS PARTY': 'Other',
    'LINCOLN LIBERTY': 'Other',
    'CICERO-BERWYN INTEGRITY': 'Other',
    'NO PARTY AFFILIATION': 'Independent',
    'INDEPENDENT DEMOCRATS-CIVIL RIGHTS': 'Independent',
    'NEW': 'Other',
    'BETTER OPTION': 'Other',
    '10TH DISTRICT UNITY': 'Other',
    'THE TEA PARTY': 'Tea Party',
    'democratic': 'Democratic',
    'democratic party': 'Democratic',
    'republican party': 'Republican',
    'non-partisan': 'Nonpartisan',
    'np': 'Nonpartisan',
    'npa': 'Nonpartisan',
    'we the people': 'We The People',
    'socialism and liberation': 'Socialism and Liberation',
    'socialist workers': 'Socialist Workers',
    'socialist equality': 'Socialist Equality',
    'justice for all': 'Justice For All',
}
