#!/usr/bin/env python3
"""
Test Pipeline Stable ID Consistency

This script tests that stable IDs are now consistent throughout the pipeline
and are only generated by the Main Pipeline.
"""

import hashlib
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def generate_main_pipeline_id(name: str, state: str, office: str, election_year: str) -> str:
    """Generate stable ID using Main Pipeline method"""
    key = f"{name}|{state}|{office}|{election_year}"
    stable_id = hashlib.md5(key.encode()).hexdigest()[:12]
    return stable_id

def generate_national_standards_id(name: str, state: str, office: str, election_year: str, county: str = None) -> str:
    """Generate stable ID using updated National Standards method"""
    # Now uses EXACTLY the same format as Main Pipeline
    key = f"{name}|{state}|{office}|{election_year}"
    stable_id = hashlib.md5(key.encode()).hexdigest()[:12]
    return stable_id

def test_pipeline_consistency():
    """Test that stable IDs are consistent throughout the pipeline"""
    logger.info("🧪 Testing Pipeline Stable ID Consistency")
    logger.info("=" * 80)
    
    # Test cases
    test_cases = [
        {
            'name': 'John Smith',
            'state': 'Alaska',
            'office': 'Governor',
            'election_year': '2024',
            'county': 'Anchorage'
        },
        {
            'name': 'Jane Doe',
            'state': 'Arizona',
            'office': 'US Senator',
            'election_year': '2024',
            'county': None
        },
        {
            'name': 'Bob Wilson',
            'state': 'Georgia',
            'office': 'US Representative',
            'election_year': '2024',
            'county': 'Fulton'
        },
        {
            'name': 'Amy Chen',
            'state': 'Illinois',
            'office': 'State Senator',
            'election_year': '2024',
            'county': None
        },
        {
            'name': 'Anthony Rodriguez',
            'state': 'New York',
            'office': 'County Executive',
            'election_year': '2024',
            'county': 'Nassau'
        }
    ]
    
    logger.info("Testing stable ID consistency across pipeline phases:")
    logger.info("-" * 60)
    
    all_match = True
    
    for i, test_case in enumerate(test_cases, 1):
        logger.info(f"\n{i}. {test_case['state']} - {test_case['name']} for {test_case['office']}")
        logger.info(f"   County: {test_case['county']}")
        
        # Generate stable ID using Main Pipeline method
        main_pipeline_id = generate_main_pipeline_id(
            test_case['name'],
            test_case['state'],
            test_case['office'],
            test_case['election_year']
        )
        
        # Generate stable ID using National Standards method
        national_standards_id = generate_national_standards_id(
            test_case['name'],
            test_case['state'],
            test_case['office'],
            test_case['election_year'],
            test_case['county']
        )
        
        # Check if they match
        ids_match = main_pipeline_id == national_standards_id
        
        logger.info(f"   Main Pipeline ID: {main_pipeline_id}")
        logger.info(f"   National Standards ID: {national_standards_id}")
        logger.info(f"   IDs Match: {'✅' if ids_match else '❌'}")
        
        if not ids_match:
            all_match = False
    
    # Test statewide deduplication scenario
    logger.info("\n" + "=" * 80)
    logger.info("🌍 Testing Statewide Deduplication with Consistent IDs")
    logger.info("=" * 80)
    
    # Create test data with same candidate in multiple counties
    test_records = [
        {
            'candidate_name': 'John Smith',
            'office': 'Governor',
            'election_year': '2024',
            'county': 'Anchorage',
            'state': 'Alaska'
        },
        {
            'candidate_name': 'John Smith',
            'office': 'Governor',
            'election_year': '2024',
            'county': 'Fairbanks',
            'state': 'Alaska'
        },
        {
            'candidate_name': 'John Smith',
            'office': 'Governor',
            'election_year': '2024',
            'county': 'Juneau',
            'state': 'Alaska'
        }
    ]
    
    logger.info("Test data created:")
    logger.info(f"  {len(test_records)} records for same candidate in different counties")
    
    # Generate stable IDs for each record
    stable_ids = []
    for record in test_records:
        stable_id = generate_main_pipeline_id(
            record['candidate_name'],
            record['state'],
            record['office'],
            record['election_year']
        )
        stable_ids.append(stable_id)
        logger.info(f"  {record['county']}: {stable_id}")
    
    # Check if all stable IDs are the same
    unique_ids = len(set(stable_ids))
    logger.info(f"\nUnique stable IDs: {unique_ids}")
    
    if unique_ids == 1:
        logger.info("✅ SUCCESS: All records have the same stable ID")
        logger.info("This enables proper statewide deduplication!")
    else:
        logger.error("❌ FAILURE: Different stable IDs generated")
        all_match = False
    
    # Show the stable ID string that was generated
    logger.info(f"\n🔍 Stable ID String Generated:")
    logger.info(f"  Input: John Smith, Alaska, Governor, 2024")
    logger.info(f"  String: John Smith|Alaska|Governor|2024")
    logger.info(f"  Hash: {stable_ids[0]}")
    
    # Final consistency check
    logger.info("\n" + "=" * 80)
    logger.info("📊 PIPELINE CONSISTENCY SUMMARY")
    logger.info("=" * 80)
    
    if all_match:
        logger.info("✅ SUCCESS: All stable IDs are consistent throughout the pipeline!")
        logger.info("🎯 Main Pipeline is now the ONLY source of stable IDs")
        logger.info("🔄 State cleaners no longer overwrite stable IDs")
        logger.info("🌍 National Standards use the same format as Main Pipeline")
    else:
        logger.error("❌ FAILURE: Stable IDs are still inconsistent")
    
    return all_match

def main():
    """Main test function"""
    try:
        success = test_pipeline_consistency()
        if success:
            logger.info("\n🎉 Pipeline consistency test PASSED!")
        else:
            logger.error("\n💥 Pipeline consistency test FAILED!")
        return success
    except Exception as e:
        logger.error(f"❌ Test failed: {e}")
        return False

if __name__ == "__main__":
    main()
